[package]
name = "nanvix-python"
version = "3.12.3"
nanvix-version = "0.12.547"

[builds]
[builds.matrix]
platforms = ["microvm"]
modes = ["standalone"]
memory = ["256mb"]

[dependencies]
cpython = "3.12.3"
